from collections.abc import Sequence

import torch
from torch import nn

from verpex.geometry.heatmaps import SoftArgmax3D
from verpex.geometry.surface import surface_project_coords
from verpex.loss.loss_modules import get_loss_fn
from verpex.models.densenet import HeatmapDenseNet


class SADenseNet(nn.Module):
    """Spatial Attention DenseNet.

    With a DenseNet-like architecture, generate a feature map and (low-resolution) heatmap for each landmark.
    Then, use the heatmap to extract a feature vector for each landmark. The soft-argmax of the heatmap defines
    the coarse landmark prediction. The feature vector generated by the heatmap-weighted sum of the feature map
    provides a feature encoding for each landmark.
    """

    def __init__(
        self,
        in_channels: int,
        n_landmarks: int,
        loss_fn: str,
        project_gt: bool = False,
        project_pred: bool = False,
        init_features: int = 64,
        feature_l: int = 256,
        growth_rate: int = 32,
        block_config: Sequence[int] = (6, 12, 24, 16),
        bn_size: int = 4,
        dropout_prob: float = 0.0,
        skip_last_transition_pool: bool = False,
        backbone: str = "densenet",
        decoder_channels: int = 128,
        use_coord_head: bool = False,
        coord_head_init_logit: float = -6.0,
        **kwargs,  # noqa: ARG002 - absorbs config keys that other coarse modules use
    ):
        super().__init__()

        self.loss_fn = get_loss_fn(loss_fn)
        self.n_landmarks = n_landmarks
        self.feature_l = feature_l
        self.use_coord_head = use_coord_head

        if backbone == "densenet":
            self.feature_extractor = HeatmapDenseNet(
                spatial_dims=3,
                in_channels=in_channels,
                n_landmarks=n_landmarks,
                init_features=init_features,
                feature_l=feature_l,
                growth_rate=growth_rate,
                block_config=block_config,
                bn_size=bn_size,
                dropout_prob=dropout_prob,
                weight_features=True,
                skip_last_transition_pool=skip_last_transition_pool,
            )
        elif backbone == "unet":
            # Imported lazily to keep the DenseNet path free of the extra symbol.
            from verpex.models.densenet import UNetHeatmapDenseNet

            self.feature_extractor = UNetHeatmapDenseNet(
                spatial_dims=3,
                in_channels=in_channels,
                n_landmarks=n_landmarks,
                init_features=init_features,
                feature_l=feature_l,
                growth_rate=growth_rate,
                block_config=block_config,
                bn_size=bn_size,
                dropout_prob=dropout_prob,
                weight_features=True,
                decoder_channels=decoder_channels,
            )
        else:
            raise ValueError(f"Unknown backbone: {backbone}")

        self.soft_argmax = SoftArgmax3D()
        self.project_gt = project_gt
        self.project_pred = project_pred

        if use_coord_head:
            from torch import nn

            self.coord_head = nn.Linear(feature_l, n_landmarks * 3)
            self.coord_gate_logit = nn.Parameter(torch.full((n_landmarks,), coord_head_init_logit))

    def forward(self, batch) -> dict:
        """Predict coarse landmark coordinates and features, adding them to ``batch``.

        Args:
            batch: A batch containing the input volume.

        Returns:
            The batch, with ``coarse_preds`` and ``coarse_features`` added.
        """
        x = batch["input"]

        heatmaps, feature_encodings, feature_maps = self.feature_extractor(
            x
        )  # (batch_size, n_landmarks, *spatial_shape), (batch_size, n_landmarks, feature_l)
        batch["heatmaps"] = heatmaps  # (batch_size, n_landmarks, *spatial_shape), save the heatmaps for visualization

        batch["feature_maps"] = feature_maps
        coarse_preds = self.soft_argmax(heatmaps)  # (batch_size, n_landmarks, 3)

        # Scale the coarse predictions to the original shape
        heatmap_shape = heatmaps.shape[2:]
        original_shape = x.shape[2:]
        scale_factor = [original_shape[i] / heatmap_shape[i] for i in range(3)]
        scaled_coarse_preds = coarse_preds * torch.tensor(scale_factor).to(coarse_preds.device)

        if self.use_coord_head:
            B = feature_maps.shape[0]
            pooled = feature_maps.mean(dim=(2, 3, 4))
            head_pred = self.coord_head(pooled).view(B, self.n_landmarks, 3)
            gate = torch.sigmoid(self.coord_gate_logit).view(1, self.n_landmarks, 1)
            scaled_coarse_preds = (1.0 - gate) * scaled_coarse_preds + gate * head_pred

        batch["coarse_preds"] = scaled_coarse_preds  # (batch_size, n_landmarks, 3)
        if self.project_pred:
            surface = batch["surface"]
            batch["coarse_preds"], _ = surface_project_coords(batch["coarse_preds"], surface)
        batch["coarse_features"] = feature_encodings  # (batch_size, n_landmarks, feature_l)

        return batch

    def calculate_loss(self, batch) -> torch.Tensor:
        """Return the coarse-stage loss for ``batch``, computed in millimetres."""
        target = batch["target"]
        surface = batch["surface"]
        if self.project_gt:
            # Project targets to surface
            target, _ = surface_project_coords(target, surface)

        # if self.project_pred:
        #    surface = batch["surface"]
        #    batch["coarse_preds"], _ = surface_project_coords(batch["coarse_preds"], surface)

        zoom = batch["zoom"].to(target.device)
        zoom = zoom.unsqueeze(1)

        coarse_preds_mm = batch["coarse_preds"] * zoom
        target_mm = target * zoom

        return self.loss_fn(
            coarse_preds_mm,
            target_mm,
            batch["loss_mask"],
            surface,
            # Set by PoiNeighborPredictionModule; absent for single-vertebra batches.
            batch.get("poi_loss_weights"),
        )

    def calculate_metrics(self, batch, mode) -> dict:
        """Return coarse-stage metrics for ``batch``, each name suffixed with ``mode``."""
        metrics = {}

        coarse_preds = batch["coarse_preds"]  # (batch_size, n_landmarks, 3)
        target = batch["target"]  # (batch_size, n_landmarks, 3)
        target_indices = batch["target_indices"]  # (batch_size, n_landmarks)
        loss_mask = batch["loss_mask"]  # (batch_size, n_landmarks)

        if self.project_gt:
            target = batch["target"]
            # Project targets to surface
            surface = batch["surface"]
            target, projection_dist = surface_project_coords(target, surface)

            metrics[f"coarse_projection_dist_{mode}"] = projection_dist.mean()

        # Consider zoom (mm per voxel)
        zoom = batch["zoom"].to(target.device)
        zoom = zoom.unsqueeze(1)

        # Calculate the mean Euclidean distance between the predicted and target landmarks
        distances = torch.norm((coarse_preds - target) * zoom, dim=-1)  # (batch_size, n_landmarks)
        distances_mean, distances_std = distances.mean(), distances.std()

        metrics[f"coarse_mean_distance_{mode}"] = distances_mean
        metrics[f"coarse_std_distance_{mode}"] = distances_std

        # Mask the distances with the loss mask
        distances_masked = distances[loss_mask]
        distances_masked_mean, distances_masked_std = (
            distances_masked.mean(),
            distances_masked.std(),
        )

        metrics[f"coarse_mean_distance_masked_{mode}"] = distances_masked_mean
        metrics[f"coarse_std_distance_masked_{mode}"] = distances_masked_std

        # Calculate mean Euclidian distance grouped by landmark type
        for landmark_type in target_indices.unique():
            landmark_mask = target_indices == landmark_type
            landmark_mask = landmark_mask * loss_mask
            distances_landmark = distances[landmark_mask]
            distances_landmark_mean = distances_landmark.mean()
            metrics[f"coarse_mean_distance_{landmark_type.item()}_{mode}"] = distances_landmark_mean

        return metrics


# returns heatmaps and a feature map that is not weighted against the heatmaps -> for ablation study
class HeatmapFeatureDenseNet(nn.Module):
    """Spatial Attention DenseNet.

    With a DenseNet-like architecture, generate a feature map (not weighted against the heatmaps) and (low-resolution) heatmap for each landmark.
    Then, use the heatmap to extract a feature vector for each landmark. The soft-argmax of the heatmap defines
    the coarse landmark prediction. The feature vector generated by the heatmap-weighted sum of the feature map
    provides a feature encoding for each landmark.
    """

    def __init__(
        self,
        in_channels: int,
        n_landmarks: int,
        loss_fn: str,
        project_gt: bool = False,
        init_features: int = 64,
        feature_l: int = 256,
        growth_rate: int = 32,
        block_config: Sequence[int] = (6, 12, 24, 16),
        bn_size: int = 4,
        dropout_prob: float = 0.0,
        **kwargs,  # noqa: ARG002 - absorbs config keys that other coarse modules use
    ):
        super().__init__()

        self.loss_fn = get_loss_fn(loss_fn)

        self.feature_extractor = HeatmapDenseNet(
            spatial_dims=3,
            in_channels=in_channels,
            n_landmarks=n_landmarks,
            init_features=init_features,
            feature_l=feature_l,
            growth_rate=growth_rate,
            block_config=block_config,
            bn_size=bn_size,
            dropout_prob=dropout_prob,
            weight_features=False,
        )

        self.soft_argmax = SoftArgmax3D()

        self.project_gt = project_gt

    def forward(self, batch) -> dict:
        """Predict coarse landmark coordinates and features, adding them to ``batch``.

        Args:
            batch: A batch containing the input volume.

        Returns:
            The batch, with ``coarse_preds`` and ``coarse_features`` added.
        """
        x = batch["input"]

        heatmaps, feature_encodings, feature_maps = self.feature_extractor(
            x
        )  # (batch_size, n_landmarks, *spatial_shape), (batch_size, n_landmarks, feature_l)
        batch["heatmaps"] = heatmaps  # (batch_size, n_landmarks, *spatial_shape), save the heatmaps for visualization
        batch["feature_maps"] = feature_maps

        coarse_preds = self.soft_argmax(heatmaps)  # (batch_size, n_landmarks, 3)

        # Scale the coarse predictions to the original shape
        heatmap_shape = heatmaps.shape[2:]
        original_shape = x.shape[2:]
        scale_factor = [original_shape[i] / heatmap_shape[i] for i in range(3)]
        scaled_coarse_preds = coarse_preds * torch.tensor(scale_factor).to(coarse_preds.device)

        batch["coarse_preds"] = scaled_coarse_preds  # (batch_size, n_landmarks, 3)
        batch["coarse_features"] = feature_encodings  # (batch_size, n_landmarks, feature_l)

        return batch

    def calculate_loss(self, batch) -> torch.Tensor:
        """Return the coarse-stage loss for ``batch``, computed in millimetres."""
        target = batch["target"]
        surface = batch["surface"]
        if self.project_gt:
            target, _ = surface_project_coords(target, surface)

        zoom = batch["zoom"].to(target.device)
        zoom = zoom.unsqueeze(1)

        coarse_preds_mm = batch["coarse_preds"] * zoom
        target_mm = target * zoom

        return self.loss_fn(
            coarse_preds_mm,
            target_mm,
            batch["loss_mask"],
            surface,
            # Set by PoiNeighborPredictionModule; absent for single-vertebra batches.
            batch.get("poi_loss_weights"),
        )

    def calculate_metrics(self, batch, mode) -> dict:
        """Return coarse-stage metrics for ``batch``, each name suffixed with ``mode``."""
        metrics = {}

        coarse_preds = batch["coarse_preds"]  # (batch_size, n_landmarks, 3)
        target = batch["target"]  # (batch_size, n_landmarks, 3)
        target_indices = batch["target_indices"]  # (batch_size, n_landmarks)
        loss_mask = batch["loss_mask"]  # (batch_size, n_landmarks)

        if self.project_gt:
            target = batch["target"]
            # Project targets to surface
            surface = batch["surface"]
            target, projection_dist = surface_project_coords(target, surface)

            metrics[f"coarse_projection_dist_{mode}"] = projection_dist.mean()

        # Consider zoom (mm per voxel)
        zoom = batch["zoom"].to(target.device)
        zoom = zoom.unsqueeze(1)

        # Calculate the mean Euclidean distance between the predicted and target landmarks
        distances = torch.norm((coarse_preds - target) * zoom, dim=-1)  # (batch_size, n_landmarks)
        distances_mean, distances_std = distances.mean(), distances.std()

        metrics[f"coarse_mean_distance_{mode}"] = distances_mean
        metrics[f"coarse_std_distance_{mode}"] = distances_std

        # Mask the distances with the loss mask
        distances_masked = distances[loss_mask]
        distances_masked_mean, distances_masked_std = (
            distances_masked.mean(),
            distances_masked.std(),
        )

        metrics[f"coarse_mean_distance_masked_{mode}"] = distances_masked_mean
        metrics[f"coarse_std_distance_masked_{mode}"] = distances_masked_std

        # Calculate mean Euclidian distance grouped by landmark type
        for landmark_type in target_indices.unique():
            landmark_mask = target_indices == landmark_type
            landmark_mask = landmark_mask * loss_mask
            distances_landmark = distances[landmark_mask]
            distances_landmark_mean = distances_landmark.mean()
            metrics[f"coarse_mean_distance_{landmark_type.item()}_{mode}"] = distances_landmark_mean

        return metrics


class SMDenseNet(nn.Module):
    """Submanifold DenseNet.

    With a SubmDenseNet, directly regress landmark coordinate estimates and landmark-wise features for refinement.
    """

    def __init__(
        self,
        in_channels: int,
        n_landmarks: int,
        loss_fn: str,
        project_gt: bool = False,
        init_features: int = 64,
        feature_l: int = 256,
        growth_rate: int = 32,
        block_config: Sequence[int] = (6, 12, 24, 16),
        bn_size: int = 4,
        dropout_prob: float = 0.0,
        **kwargs,  # noqa: ARG002 - absorbs config keys that other coarse modules use
    ):
        super().__init__()

        self.loss_fn = get_loss_fn(loss_fn)

        # Imported here, not at module scope: subm_densenet subclasses spconv types at
        # class-definition time, so importing it would make spconv a hard dependency
        # of the whole package rather than of these two sparse backbones.
        from verpex.models.subm_densenet import SubmDenseNet

        self.feature_extractor = SubmDenseNet(
            in_channels=in_channels,
            n_landmarks=n_landmarks,
            init_features=init_features,
            feature_l=feature_l,
            growth_rate=growth_rate,
            block_config=block_config,
            bn_size=bn_size,
            dropout_prob=dropout_prob,
        )

        self.project_gt = project_gt

    def forward(self, batch) -> dict:
        """Predict coarse landmark coordinates and features, adding them to ``batch``.

        Args:
            batch: A batch containing the input volume.

        Returns:
            The batch, with ``coarse_preds`` and ``coarse_features`` added.
        """
        x = batch["input"]
        coarse_preds, feature_encodings = self.feature_extractor(x)

        batch["coarse_preds"] = coarse_preds
        batch["coarse_features"] = feature_encodings

        return batch

    def calculate_loss(self, batch) -> torch.Tensor:
        """Return the coarse-stage loss for ``batch``, computed in millimetres."""
        target = batch["target"]
        surface = batch["surface"]
        if self.project_gt:
            target, _ = surface_project_coords(target, surface)

        # Scale to millimetres, as SADenseNet does, so the loss means the same thing
        # at any voxel spacing and is comparable across coarse modules.
        zoom = batch["zoom"].to(target.device).unsqueeze(1)

        return self.loss_fn(
            batch["coarse_preds"] * zoom,
            target * zoom,
            batch["loss_mask"],
            surface,
            # Set by PoiNeighborPredictionModule; absent for single-vertebra batches.
            batch.get("poi_loss_weights"),
        )

    def calculate_metrics(self, batch, mode) -> dict:
        """Return coarse-stage metrics for ``batch``, each name suffixed with ``mode``."""
        metrics = {}

        coarse_preds = batch["coarse_preds"]  # (batch_size, n_landmarks, 3)
        target = batch["target"]  # (batch_size, n_landmarks, 3)
        target_indices = batch["target_indices"]  # (batch_size, n_landmarks)
        loss_mask = batch["loss_mask"]  # (batch_size, n_landmarks)

        if self.project_gt:
            target = batch["target"]
            # Project targets to surface
            surface = batch["surface"]
            target, projection_dist = surface_project_coords(target, surface)

            metrics[f"coarse_projection_dist_{mode}"] = projection_dist.mean()

        # Calculate the mean Euclidean distance between the predicted and target landmarks
        # Millimetres, as in the dense coarse modules, so the numbers logged by
        # the sparse backbones are comparable with everything else.
        zoom = batch["zoom"].to(target.device).unsqueeze(1)
        distances = torch.norm((coarse_preds - target) * zoom, dim=-1)

        distances_mean, distances_std = distances.mean(), distances.std()

        metrics[f"coarse_mean_distance_{mode}"] = distances_mean
        metrics[f"coarse_std_distance_{mode}"] = distances_std

        # Mask the distances with the loss mask
        distances_masked = distances[loss_mask]
        distances_masked_mean, distances_masked_std = (
            distances_masked.mean(),
            distances_masked.std(),
        )

        metrics[f"coarse_mean_distance_masked_{mode}"] = distances_masked_mean
        metrics[f"coarse_std_distance_masked_{mode}"] = distances_masked_std

        # Calculate mean Euclidian distance grouped by landmark type
        for landmark_type in target_indices.unique():
            landmark_mask = target_indices == landmark_type
            landmark_mask = landmark_mask * loss_mask
            distances_landmark = distances[landmark_mask]
            distances_landmark_mean = distances_landmark.mean()
            metrics[f"coarse_mean_distance_{landmark_type.item()}_{mode}"] = distances_landmark_mean

        return metrics


class SMSADenseNet(nn.Module):
    """Submanifold Spatial Attention DenseNet.

    With a SubmDenseNet, generate a feature map and (low-resolution) heatmap for each landmark.
    Then, use the heatmap to extract a feature vector for each landmark. The soft-argmax of the heatmap defines
    the coarse landmark prediction. The feature vector generated by the heatmap-weighted sum of the feature map
    provides a feature encoding for each landmark.
    """

    def __init__(
        self,
        in_channels: int,
        n_landmarks: int,
        loss_fn: str,
        project_gt: bool = False,
        init_features: int = 64,
        feature_l: int = 256,
        growth_rate: int = 32,
        block_config: Sequence[int] = (6, 12, 24, 16),
        bn_size: int = 4,
        dropout_prob: float = 0.0,
        **kwargs,  # noqa: ARG002 - absorbs config keys that other coarse modules use
    ):
        super().__init__()

        self.loss_fn = get_loss_fn(loss_fn)

        self.project_gt = project_gt

        # See the note in SMDenseNet: spconv is only required by the sparse backbones.
        from verpex.models.subm_densenet import HeatmapSubmDenseNet

        self.feature_extractor = HeatmapSubmDenseNet(
            in_channels=in_channels,
            n_landmarks=n_landmarks,
            init_features=init_features,
            feature_l=feature_l,
            growth_rate=growth_rate,
            block_config=block_config,
            bn_size=bn_size,
            dropout_prob=dropout_prob,
        )

        self.soft_argmax = SoftArgmax3D()

    def forward(self, batch) -> dict:
        """Predict coarse landmark coordinates and features, adding them to ``batch``.

        Args:
            batch: A batch containing the input volume.

        Returns:
            The batch, with ``coarse_preds`` and ``coarse_features`` added.
        """
        # Only keep input that lies on the surface
        x = batch["input"] * batch["surface"]
        heatmaps, feature_encodings = self.feature_extractor(
            x
        )  # (batch_size, n_landmarks, *spatial_shape), (batch_size, n_landmarks, feature_l)
        batch["heatmaps"] = heatmaps  # (batch_size, n_landmarks, *spatial_shape), save the heatmaps for visualization
        coarse_preds = self.soft_argmax(heatmaps)  # (batch_size, n_landmarks, 3)

        # Scale the coarse predictions to the original shape
        heatmap_shape = heatmaps.shape[2:]
        original_shape = x.shape[2:]
        scale_factor = [original_shape[i] / heatmap_shape[i] for i in range(3)]
        scaled_coarse_preds = coarse_preds * torch.tensor(scale_factor).to(coarse_preds.device)

        batch["coarse_preds"] = scaled_coarse_preds  # (batch_size, n_landmarks, 3)
        batch["coarse_features"] = feature_encodings  # (batch_size, n_landmarks, feature_l)

        return batch

    def calculate_loss(self, batch) -> torch.Tensor:
        """Return the coarse-stage loss for ``batch``, computed in millimetres."""
        target = batch["target"]
        surface = batch["surface"]
        if self.project_gt:
            target, _ = surface_project_coords(target, surface)

        # Scale to millimetres, as SADenseNet does, so the loss means the same thing
        # at any voxel spacing and is comparable across coarse modules.
        zoom = batch["zoom"].to(target.device).unsqueeze(1)

        return self.loss_fn(
            batch["coarse_preds"] * zoom,
            target * zoom,
            batch["loss_mask"],
            surface,
            # Set by PoiNeighborPredictionModule; absent for single-vertebra batches.
            batch.get("poi_loss_weights"),
        )

    def calculate_metrics(self, batch, mode) -> dict:
        """Return coarse-stage metrics for ``batch``, each name suffixed with ``mode``."""
        metrics = {}

        coarse_preds = batch["coarse_preds"]  # (batch_size, n_landmarks, 3)
        target = batch["target"]  # (batch_size, n_landmarks, 3)
        target_indices = batch["target_indices"]  # (batch_size, n_landmarks)
        loss_mask = batch["loss_mask"]  # (batch_size, n_landmarks)

        if self.project_gt:
            target = batch["target"]
            # Project targets to surface
            surface = batch["surface"]
            target, projection_dist = surface_project_coords(target, surface)

            metrics[f"coarse_projection_dist_{mode}"] = projection_dist.mean()

        # Calculate the mean Euclidean distance between the predicted and target landmarks
        # Millimetres, as in the dense coarse modules, so the numbers logged by
        # the sparse backbones are comparable with everything else.
        zoom = batch["zoom"].to(target.device).unsqueeze(1)
        distances = torch.norm((coarse_preds - target) * zoom, dim=-1)
        distances_mean, distances_std = distances.mean(), distances.std()

        metrics[f"coarse_mean_distance_{mode}"] = distances_mean
        metrics[f"coarse_std_distance_{mode}"] = distances_std

        # Mask the distances with the loss mask
        distances_masked = distances[loss_mask]
        distances_masked_mean, distances_masked_std = (
            distances_masked.mean(),
            distances_masked.std(),
        )

        metrics[f"coarse_mean_distance_masked_{mode}"] = distances_masked_mean
        metrics[f"coarse_std_distance_masked_{mode}"] = distances_masked_std

        # Calculate mean Euclidian distance grouped by landmark type
        for landmark_type in target_indices.unique():
            landmark_mask = target_indices == landmark_type
            landmark_mask = landmark_mask * loss_mask
            distances_landmark = distances[landmark_mask]
            distances_landmark_mean = distances_landmark.mean()
            metrics[f"coarse_mean_distance_{landmark_type.item()}_{mode}"] = distances_landmark_mean

        return metrics


#: Config ``"type"`` string -> coarse (feature-extraction) module.
#: Consumed by :func:`verpex.modules.poi_module.create_feature_extraction_module`.
FEATURE_EXTRACTION_MODULES = {
    "SADenseNet": SADenseNet,
    "HeatmapFeatureDenseNet": HeatmapFeatureDenseNet,
    "SMDenseNet": SMDenseNet,
    "SMSADenseNet": SMSADenseNet,
}
